version: '3.8'

services:
  postgres:
    container_name: postgres-sql-1
    image: postgres
    environment:
      POSTGRES_USER: kalemz
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hackemotions
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shopper-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-shopper-1
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - shopper-demo

networks:
  shopper-demo:
    driver: bridge

volumes:
  postgres:
    driver: local