services:
  postgres:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: kalemz
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hackemotions
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hackemotions-demo
    restart: unless-stopped

networks:
  hackemotions-demo:
    driver: bridge

volumes:
  postgres:
    driver: local