version: '3.8'

services:
  # Spring Boot application
  app:
    image: openjdk:17-jdk
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/hackemotion
    ports:
      - "8080:8080"
    depends_on:
      - db

  # MongoDB database
  db:
    image: mongo:latest
    container_name: mongodb
    #environment:
     # MONGO_INITDB_ROOT_USERNAME: your_username
      #MONGO_INITDB_ROOT_PASSWORD: your_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
