application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 900000 # 15m
      refresh-token:
        expiration: 604800000 # 7d
  mailing:
    frontend:
      activation-url: http://localhost:5173/activate-account
server:
  port: 8088

spring:
  mail:
    host: localhost
    port: 1025
    username: user
    password: user
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 3000
        timeout: 2000
        writetimeout: 3000